server:
  port: ${PORT:8888}
  shutdown: graceful

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:user}
      password: ${CONFIG_SERVER_PASSWORD:12345}

  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: config-server

---

spring:
  config:
    activate:
      on-profile: test

---

spring:
  config:
    activate:
      on-profile: prod

---